maxhoesel-ansible/ansible-collection-smallstep

docs/CA_SERVER.md
molecule/default/converge.yml
roles/ca_server/tasks/init.yml
roles/ca_server/tasks/install.yml

The pexept module can sometimes cause errors when running
through the Ansible builtin except module
(https://github.com/ansible/ansible/issues/29351).
To prevent these issues from occuring and messing with the CI,
we remove the except module call and replace it with a shell
call to except directly. This also removes the pexcept package
as a dependency from ca_server.

Fix UnicodeDecodeError by removing pexcept dependency

---

docs/CA_SERVER.md
docs/STEP_CLIENT.md
molecule/default/converge.yml
roles/ca_server/handlers/main.yml
roles/ca_server/tasks/install.yml
roles/ca_server/tasks/main.yml
roles/ca_server/tasks/service.yml
roles/step_client/tasks/install.yml
roles/step_client/tasks/root_cert.yml

BREAKING CHANGE: From now on, the roles in this collection expect
to be running with root privileges, so you'll need to call them with
`become: yes`. This removes a few edge cases and other issues

refactor: remove `become` directives from roles

---

galaxy.yml
roles/step_acme_cert/tasks/main.yml

This commit removes the dependency on community.crypto
(and by extension, the cryptography python package).
It turns out that step-cli has all the required functionality built-in,
so we use that instead

fix(step_acme_cert): remove community.cryto dep

---

roles/step_ca/tasks/main.yml
roles/step_cli/tasks/main.yml

As described in  #61 , using `become: yes` on tasks with `delegate_to: localhost` can break workflows with different machines having different `sudo` passwords. The only two tasks with this behavior are `uri` modules, that don't require privilege escalation in the first place. This PR seeks to resolve the issue by disabling privilege escalation for those tasks explicitly, as it is not required for the functionality of the `uri` module

Don't use privilege escalation when delegating locally

---

plugins/modules/step_ca_bootstrap.py

It seems that only catching OSError isn't sufficient on some systems
and python versions, as this module currently crashes under Ubuntu 18.04
with a FileNotFoundError that is not caught properly. This patch addresses that.

fix(step_ca_boostrap): don't fail on ubuntu 18.04

---

roles/step_acme_cert/molecule/default/molecule.yml
roles/step_acme_cert/tasks/main.yml
roles/step_bootstrap_host/molecule/default/molecule.yml
roles/step_ca/molecule/default/molecule.yml
roles/step_ca/tasks/main.yml
roles/step_cli/molecule/default/molecule.yml
roles/step_cli/tasks/capabilities.yml
roles/step_cli/tasks/main.yml

This change introduces support for running all roles in this collection in --check mode after being run normally at least once. This is useful in CI/CD workflows where changes are first tested in a `--check` dry-run before then being applied. See https://github.com/maxhoesel/ansible-collection-smallstep/issues/65 for more background on this.
Note that this change does not enable dry-run installations from scratch.
This PR also includes https://github.com/maxhoesel/ansible-collection-smallstep/pull/66

Support `--check` mode for all roles once configured

---

roles/step_bootstrap_host/README.md
roles/step_bootstrap_host/defaults/main.yml
roles/step_bootstrap_host/tasks/main.yml

The module (`step_ca_boostrap.py`) underlying the `step_boostrap_role` has an `force` option, but it is not exposed in the role.  This creates a variable for role users to modify, which defaults to `no`, and passes that value to the module.  Documentation has been added as well.
This feature allows one to change the CA URL or point at a different CA simply by calling the `bootstrap` role again.
/resolves #73

feat(step_boostrap_host): pass `force` to underlying module (#73)

---

roles/step_acme_cert/defaults/main.yml
roles/step_acme_cert/tasks/get_cert.yml

Use the `| combine(dict)` feature of Jinja to support full defaults for the `step_acme_cert_certfile` and `_keyfile` variables.  Now, only the keys that need overriding need a value. E.g. instead of:
- name: step-client | test cert creation and renewal
include_role:
name: maxhoesel.smallstep.step_acme_cert
vars:
step_acme_cert_certfile:
path: "{{ step_cert_directory }}/step-test-cert.crt"
owner: root
group: root
mode: 644
step_acme_cert_keyfile:
path: "{{ step_cert_directory }}/step-test-cert.key"
owner: root
group: root
mode: 600
... one can simplify to only:
- name: step-client | test cert creation and renewal
include_role:
name: maxhoesel.smallstep.step_acme_cert
vars:
step_acme_cert_certfile:
path: "{{ step_cert_directory }}/step-test-cert.crt"
step_acme_cert_keyfile:
path: "{{ …

feat(step_acme_cert): better default value support for cert gen (#81)

---

plugins/modules/step_ca_certificate.py
plugins/modules/step_ca_token.py

Added `no_log=False` to a couple of places where the name of the variables look like passwords, but are not.
FIXES: #75

fix(step_ca): eliminate spurious Ansible "password" warnings

---

plugins/module_utils/run.py

This fix captures a different or updated error message from
`step-cli` when it attempts to open `/dev/tty`:
open /dev/tty: no such device or address
Ideally, `step-cli` would provide a way to avoid this entirely; c.f:
- https://github.com/smallstep/cli/issues/502
/resolves #72

fix(utils): capture step_cli attempt to open tty (#72)

---

roles/step_bootstrap_host/molecule/default/verify.yml
roles/step_bootstrap_host/tasks/main.yml

The smallstep tools can be configured to use a different path
than the default $HOME/.step/ using the $STEPPATH variable.
Until now, the certificate install check in step_bootstrap_host
did not respect this variable and could thus have failed on
hosts with STEPPATH set.
In addition, this change also removes the need for the statefile
inside of .step that was previously used by this role for idempotency
purposes. Instead, we can use step-clis builtin certificate check
to see if the CA cert is already installed.
Partially fixes #83

fix(step_bootstrap_host): properly support non-default STEPPATH 

---

roles/step_bootstrap_host/tasks/main.yml

This amends the checks and installation of STEP CA Root certificate to use STEPPATH if set.  If not set, will mimic the `step-cli` behavior and default to `$HOME/.step`.
Note that the previous implementation utilized the ansible `lookup(env, 'STEPPATH')` filter, but that will not work for environment variables set via the `environment:` block, per the documentation:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html
> The environment: keyword does not affect Ansible itself, Ansible
> configuration settings, the environment for other users, or the
> execution of other plugins like lookups and filters.
What this does allow is setting of the environment variable at a play or task level; e.g.:
```yaml
- hosts: step_client
become: yes
environment:
STEPPATH: "{{ …
```

fix(step_bootstrap_host): support STEPPATH ENV VAR

---

roles/step_acme_cert/README.md
roles/step_ca/README.md
roles/step_ca/defaults/main.yml
roles/step_ca/tasks/check.yml
roles/step_ca/tasks/init.yml

This PR switches the undefined-by-default variables in `step_ca` (such as `step_ca_url`) from empty strings to actual undefined variables. The main motivation for this change is consistency and readability - these values aren't just empty by default, they don't exist in the first place.

fix(step_ca): make unset defaults actually undefined instead of ""

---

CONTRIBUTING.md
README.md
plugins/doc_fragments/ca_connection_hybrid.py
roles/step_acme_cert/README.md
roles/step_acme_cert/defaults/main.yml
roles/step_acme_cert/molecule/default/converge.yml
roles/step_acme_cert/molecule/default/prepare.yml
roles/step_acme_cert/tasks/get_cert.yml
roles/step_acme_cert/tasks/main.yml
roles/step_acme_cert/tasks/renewal.yml
roles/step_acme_cert/templates/step-renew.service.j2
roles/step_bootstrap_host/README.md
roles/step_bootstrap_host/defaults/main.yml
roles/step_bootstrap_host/molecule/default/converge.yml
roles/step_bootstrap_host/molecule/default/verify.yml
roles/step_bootstrap_host/tasks/main.yml

This PR adds support for a custom STEPPATH in all roles that use the step-cli config.
Fixes #83 
@eengstrom can you confirm that this works for you?

feat: add STEPPATH support to bootstrap_host and acme_cert

---

roles/step_acme_cert/tasks/check.yml
roles/step_bootstrap_host/molecule/default/verify.yml
roles/step_bootstrap_host/tasks/check.yml
roles/step_bootstrap_host/tasks/main.yml
roles/step_ca/tasks/check.yml

When looking for the step-cli at the begging of a role,
we can use the "command" shell builtin to check for the binaries presence
instead of calling it directly.
This has the advantage of elminating the ugly "failed" task that would
normally occur when running the step_cli or step_bootstrap_hosts roles
for the first time. For consistencys sake, we also use this new method
in roles like step_acme_cert that error out upon not finding step-cli.
We can use the same pattern to also catch the error thrown by step-cli
upon finding an invalid/not-yet-installed ca cert in step_bootstrap_host.
Fixes https://github.com/maxhoesel/ansible-collection-smallstep/issues/96,

fix: eliminate "expected errors" when looking for step-cli/certs

---

.github/workflows/ci.yml
tox.ini

With release 1.6 out, we can now install tox-ansible regularly again.
Fixes https://github.com/maxhoesel/ansible-collection-smallstep/issues/100

ci: remove tox-ansible workaround

---

roles/step_bootstrap_host/tasks/check.yml
roles/step_ca/tasks/check.yml

This change ensures that step-cli is *always* at the version specified in the role variables.
Previously, this collection would not upgrade step-cli if a version was already installed. By removing this check, we always upgrade to the desired version

always upgrade step-cli to specified version

---

CONTRIBUTING.md
roles/step_bootstrap_host/README.md
roles/step_bootstrap_host/defaults/main.yml
roles/step_bootstrap_host/molecule/default/converge.yml
roles/step_bootstrap_host/molecule/default/verify.yml
roles/step_bootstrap_host/tasks/main.yml
roles/step_ca/README.md
roles/step_ca/defaults/main.yml
roles/step_ca/vars/main.yml
roles/step_cli/README.md
roles/step_cli/defaults/main.yml
roles/step_cli/molecule/default/converge.yml
roles/step_cli/molecule/default/verify.yml
roles/step_cli/tasks/install.yml
roles/step_cli/vars/main.yml

With this change, we now install step-cli/ca to the dir defined by the user.
This also fixes a potential issue where if a user specified a custom
executable via `step_bootstrap_host` that did not exist,
the role would have just installed step-cli to the default directory
instead of `step_cli_executable`.
From now on, we will determine the installation for step-cli path as follows:
- Use `step_cli_executable` if it is a path
- Use `step_cli_install_dir` + `step_cli_executable` if the latter is a filename
For step-ca, we simply require `step_ca_executable` to be an absolute path.
This is not possible for step-cli without breaking backwards compatibility as the variable
could also be a filename.

make step-cli/ca install dir user-selectable

---

roles/step_ca/README.md
roles/step_ca/tasks/init.yml
roles/step_ca/tasks/install.yml

This change removes the need to shell out to `except`
when initializing the CA and setting up password files.
Newer versions of the step crypto change-pass command
include an option to pass the password via a file instead of interactive input.
As this removes the need for `except`, we should use that.

replace `except` with --password-file flags

---

roles/step_acme_cert/README.md
roles/step_acme_cert/molecule/default/molecule.yml
roles/step_acme_cert/molecule/default/prepare.yml
roles/step_bootstrap_host/README.md
roles/step_bootstrap_host/molecule/default/molecule.yml
roles/step_bootstrap_host/molecule/default/prepare.yml
roles/step_ca/README.md
roles/step_ca/molecule/default/molecule.yml
roles/step_ca/molecule/default/prepare.yml
roles/step_ca/tasks/install.yml
roles/step_cli/README.md
roles/step_cli/molecule/default/molecule.yml
roles/step_cli/molecule/default/prepare.yml
roles/step_cli/tasks/install.yml

This change adds official support for Fedora 36 to all the roles contained in this collection.
This should also fix #177

Roles: add Fedora 36 support

---

roles/step_ca/tasks/init.yml

When following the instructions for [setting up a step ca installation](https://github.com/maxhoesel-ansible/ansible-collection-smallstep#create-a-ca) the CA role will bug out due to the variables for previous root files not being there.
```
TASK [maxhoesel.smallstep.step_ca : Initialize CA] ***************************************************************************************************************************
Mittwoch 07 September 2022  21:39:24 +0200 (0:00:00.022)       0:00:40.066 **** 
fatal: [ca]: FAILED! => 
msg: |-
The task includes an option with an undefined variable. The error was: 'step_ca_existing_root_file' is undefined
The error appears to be in '/home/danielsreichenbach/Projects/kogito/infrastructure/ansible/maasstar/collections/ansible_collections/maxhoesel/smallstep/rol …
```

Fixed missing check for existing root files

---

roles/step_ca/tasks/install.yml
tests/constants.sh

This change bumps the supported step version to 0.23, neccessitating  a new release of this collection

Sync collection with upstream version 0.23

---

.gitignore
CONTRIBUTING.md
requirements-molecule.txt
roles/step_acme_cert/molecule/default/molecule.yml
roles/step_acme_cert/molecule/default/prepare.yml
roles/step_bootstrap_host/molecule/default/converge.yml
roles/step_bootstrap_host/molecule/default/molecule.yml
roles/step_ca/molecule/default/molecule.yml
roles/step_cli/molecule/default/molecule.yml
scripts/setup.sh
tests/integration/docker/step-ca-ansible/README.md
tests/integration/integration_config.yml.template
tests/test-modules
tests/test-modules-integration
tox.ini

As discussed in #105, molecule-docker is no longer a suitable driver for our needs (specifically due to systemd support), so it's about time we switched to a container runtime that actually supports systemd.
With the 4.0 release, podman is finally up to the task of running our integration tests.
This change migrates molecule and ansible-test to podman and updates the contributing documentation to account for the changes.
Users that wish to test the collection locally can do so by "just" installing podman, no need to modify their docker install
(or use the god-awful unified_cgroup_hierarchy hack anymore).
However, as podman 4.0 is still relatively recent, no major distros (aside from Arch) have it in their repositories yet.
This is bound to change with the next major release of these …

Switch to podman for testing collection roles/modules

---

tests/constants.sh

This pushes the collection version to 0.24, with an according version push for the collection

bump collection to step tools 0.24

---

.circleci/config.yml
tests/test-modules-integration
tests/test-modules-sanity
tests/test-roles
tests/util.sh

Our CI (especially the tox tests) sometimes fail due to transient network failures, etc. To improve resilience a bit, add some basic retry logic to the big tasks themselves.

Add Retry functionality to CI

---

roles/step_bootstrap_host/README.md
roles/step_bootstrap_host/defaults/main.yml
roles/step_bootstrap_host/meta/argument_specs.yml
roles/step_bootstrap_host/tasks/check.yml
roles/step_ca/README.md
roles/step_ca/defaults/main.yml
roles/step_ca/meta/argument_specs.yml
roles/step_ca/tasks/check.yml

This PR adds a `step_cli_install` option to both `step_bootstrap_host` and `step_ca`.
This is intended for cases where the user might already have `step-cli` installed and doesn't want the roles to touch it.

(roles): Add option to skip installing step-cli

---

roles/step_acme_cert/tasks/main.yml

One task doesn't use the `step_cli_executable` variable and has the command hard-coded instead. This PR fixes that :)

fix: replace hard-coded step-cli by var

---

roles/step_acme_cert/README.md
roles/step_acme_cert/molecule/converge.yml
roles/step_acme_cert/molecule/verify.yml
roles/step_acme_cert/tasks/renewal.yml
roles/step_acme_cert/templates/sudo-renewal.j2

Fixes #316 
By using an alias name based on the renewal service name, multiple services can co-exist in the sudoers configuration at the same time. The user is still required to set a unique name for each renewal service instance, as mentioned in the README.
To ensure that any old configs are wiped, this PR also slightly changes the naming scheme for the sudoer files

step_acme_cert: use different sudo alias name for separate instances

---

roles/step_acme_cert/tasks/renewal.yml

This fixes an issue where sudo would warn about duplicate aliases being set due to a configuration file name change

step_acme_cert: always remove old sudoer aliases

---

.circleci/config.yml
CONTRIBUTING.md
README.md
tests/conftest.py

A spart of the effort for the 1.x release, most of the modules and module_utils are going to see a significant rework.
One of the key improvements will be the inclusion of type hints, which require Python 3.7.
The current state of the refactor can be seen here: https://github.com/maxhoesel/ansible-collection-smallstep-fork/tree/refactor_modules
This PR drops 3.6 from the modules tests. Future PRs may also drop support for distributions still running Python 3.6

breaking: bump node python requirement to 3.7

---

plugins/modules/step_ca_bootstrap.py
plugins/modules/step_ca_certificate.py
plugins/modules/step_ca_provisioner.py
plugins/modules/step_ca_renew.py
plugins/modules/step_ca_revoke.py
plugins/modules/step_ca_token.py
tests/integration/targets/step_ca_revoke/tasks/main.yml

This PR removes the `stdout` and `stderr` parameters from all module return values. These values were never documented, but since someone might still have used them this considered a breaking change nonetheless.
In addition, `step_ca_revoke` is now idempotent by checking if the certificate actually got revoked or not

modules: remove stderr/stdout from output, make revoke idempotent

---

roles/step_ca/tasks/install.yml
roles/step_cli/tasks/install.yml

This addresses a potentially security-critical issue described in #371 , where due to unchanged ownership, a normal user may have been able to modify/replace the step-cli and step-ca binaries.

roles: ensure binaries are owned by root

---

roles/step_ca/tasks/init.yml

Single character change to match the argument "--new-password-file" when updating the intermediate key file password.

Add missing dash to new-password-file arg when setting intermediate key passwd

---

roles/step_acme_cert/tasks/check.yml
roles/step_cli/tasks/install.yml

this patch renames the internal variables used by the roles to determine
whether step-cli is installed to a different value than the user-facing
`step_cli_install` variable that toggles installation.
Fixes a case where a user that set step_cli_install as a role variable
in their playbook would get errors about step_cli_install being a bool
and not having an RC object due to the internal var being overwritten.

roles: fix step_cli_install var being overwritten

---

roles/step_acme_cert/README.md
roles/step_acme_cert/molecule/default/molecule.yml
roles/step_acme_cert/molecule/non_root/molecule.yml
roles/step_bootstrap_host/README.md
roles/step_bootstrap_host/molecule/default/molecule.yml
roles/step_bootstrap_host/molecule/multi_user/molecule.yml
roles/step_ca/README.md
roles/step_ca/molecule/default/molecule.yml
roles/step_cli/README.md
roles/step_cli/molecule/default/molecule.yml

This commit updates the tested distributions to Debian 12 and
Fedora 39. The following distros will soon see the end of their
mainstream support period, so we drop them from our test roster:
Ubuntu 18.04
Debian 10
RockyLinux/AlmaLinux 8
Ubuntu and RockyLinux in particular still shipped with older python
versions than we now officially support (3.6 vs 3.7), so removing them
should prevent conflicts and confusion.
Fedora 36 has already lost support status over a year ago, so about time
we update that version to something more recent.

roles: update supported distros, remove older distros

---

plugins/module_utils/cli_wrapper.py
plugins/modules/step_ca_bootstrap.py
plugins/modules/step_ca_certificate.py
plugins/modules/step_ca_provisioner.py
plugins/modules/step_ca_renew.py
plugins/modules/step_ca_token.py
plugins/modules/step_certificate_info.py

In preparation for addressing #352, this commit changes the workflow for executing step-cli commands into a builder pattern:
Modules now first construct a command with all parameters already passed in, before then executing it with a single invocation.
This is less error-prone than the old style of moving around raw dicts created with build_params() and allows us to extend the abstraction with new features in the future.
For now, only the new tmpfile is included, which will allow modules to easily pass in strings such as passwords through temporary files.

modules: refactor cli_wrapper to Command-based approach

---

roles/step_ca/README.md
roles/step_ca/defaults/main.yml
roles/step_ca/meta/argument_specs.yml

The `step_ca` role currently assumes that any step-ca host will always have at least one IPv4 address assigned. However, some users may want to run an IPv6-only CA, which fails with the current default setting for `step_ca_dns`. 
This change addresses that by changing `step_ca_dns` to opportunisitically include default IPv4 and IPv6 addresses, if present. If this behavior is undesirable, users can always override `step_ca_dns` themselves
Fixes #385.

step_ca: fix failure on ipv6-only networks

---

plugins/module_utils/cli_wrapper.py
plugins/module_utils/helpers.py
plugins/module_utils/params/ca_admin.py
plugins/module_utils/params/ca_connection.py
plugins/module_utils/params/params_helper.py
plugins/modules/step_ca_bootstrap.py
plugins/modules/step_ca_certificate.py
plugins/modules/step_ca_provisioner.py
plugins/modules/step_ca_renew.py
plugins/modules/step_ca_token.py
plugins/modules/step_certificate_info.py

More prep work for #352, this allows module param helpers to supply a fully composable CliArgs object that can include both tempfiles and regular args

modules: factor out cliargs into separate dataclass

---

plugins/doc_fragments/ca_admin.py
plugins/module_utils/cli_wrapper.py
plugins/module_utils/params/ca_admin.py
plugins/modules/step_ca_certificate.py
plugins/modules/step_ca_provisioner.py
plugins/modules/step_ca_renew.py
plugins/modules/step_ca_token.py
tests/integration/targets/step_ca_certificate/tasks/main.yml
tests/integration/targets/step_ca_provisioner/tasks/main.yml
tests/integration/targets/step_ca_renew/tasks/main.yml
tests/integration/targets/step_ca_token/tasks/main.yml

this PR adds a `_password` parameter to go along with every currently existing `password_file` module parameter. As discussed in #352, this makes passing in passwords to tasks much more convenient, as users no longer need to create and delete password files manually.
To ensure no sensitive password files remain on the system, they are created in a temporary directory that is handled through a context manager, see #398.
fixes #352

modules: add `_password` args as alternative to password_files

---

roles/step_acme_cert/README.md
roles/step_acme_cert/molecule/default/molecule.yml
roles/step_acme_cert/molecule/non_root/molecule.yml
roles/step_bootstrap_host/README.md
roles/step_bootstrap_host/molecule/default/molecule.yml
roles/step_bootstrap_host/molecule/multi_user/molecule.yml
roles/step_ca/README.md
roles/step_ca/molecule/default/molecule.yml
roles/step_cli/README.md
roles/step_cli/molecule/default/molecule.yml

This path updates the tested fedora and ubuntu versions to be in line with current releases

roles: bump supported distributions

---

roles/step_acme_cert/molecule/verify.yml

Sometimes, the nginx service gets stuck in a non-started state
and i have no idea why.
Since the failure is only sporadic, add a debug function to gather more info

add debug message to flaky molecule test

---

roles/step_acme_cert/handlers/main.yml
roles/step_acme_cert/tasks/main.yml

This fixes #450 by always restarting the `step-renew` service after certificate re-issuance, and reloading desired services just like the `step-renew` service would.

Restart renewal service after issuing new cert with CA, reload affected services
